/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativelib_NativeLibrary */

#ifndef _Included_nativelib_NativeLibrary
#define _Included_nativelib_NativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativelib_NativeLibrary
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativelib_NativeLibrary_nativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
